package com.example.a501_10.app_class_portfolio.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PLACE".
 */
@Entity
public class Place {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private java.util.Date created_at;

    @NotNull
    private java.util.Date updated_at;
    private String name;
    private String desc;
    private String img_name;
    private String phone;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Place() {
    }

    public Place(Long id) {
        this.id = id;
    }

    @Generated
    public Place(Long id, java.util.Date created_at, java.util.Date updated_at, String name, String desc, String img_name, String phone) {
        this.id = id;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.name = name;
        this.desc = desc;
        this.img_name = img_name;
        this.phone = phone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public java.util.Date getCreated_at() {
        return created_at;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreated_at(@NotNull java.util.Date created_at) {
        this.created_at = created_at;
    }

    @NotNull
    public java.util.Date getUpdated_at() {
        return updated_at;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpdated_at(@NotNull java.util.Date updated_at) {
        this.updated_at = updated_at;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getImg_name() {
        return img_name;
    }

    public void setImg_name(String img_name) {
        this.img_name = img_name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
